#!/bin/sh
# Sessionlog setup script for Claude Code Web (ccweb)
#
# This script is executed as a SessionStart hook in Claude Code Web sessions.
# It installs the sessionlog CLI, enables it for the current repo, and
# configures GitHub direct-push access for session/checkpoint branches.
#
# Generated by: sessionlog setup-ccweb
set -e

# Only run in remote Claude Code environments
if [ "$CLAUDE_CODE_REMOTE" != "true" ]; then
  exit 0
fi

# ============================================================================
# Configuration
# ============================================================================

# Branch prefixes allowed for direct push (space-separated).
# Edit this to allow additional prefixes beyond sessionlog's defaults.
ALLOWED_PUSH_PREFIXES="sessionlog/ claude/"

# ============================================================================
# Install sessionlog CLI
# ============================================================================

if ! command -v sessionlog >/dev/null 2>&1; then
  echo "[sessionlog-ccweb] Installing sessionlog CLI..."
  npm install -g sessionlog 2>/dev/null || {
    echo "[sessionlog-ccweb] Warning: Failed to install sessionlog globally, trying npx..."
  }
fi

# ============================================================================
# Enable sessionlog for this repository
# ============================================================================

if command -v sessionlog >/dev/null 2>&1; then
  # Enable with Claude Code agent (idempotent)
  sessionlog enable --agent claude-code --local 2>/dev/null || true
  echo "[sessionlog-ccweb] Sessionlog enabled."
else
  echo "[sessionlog-ccweb] Warning: sessionlog not found. Skipping enable."
fi

# ============================================================================
# Configure GitHub direct-push access
# ============================================================================

# The ccweb proxy only allows pushing to the current working branch.
# We need direct GitHub access to push sessionlog shadow branches.

if [ -n "$GITHUB_TOKEN" ]; then
  # Get the remote URL and extract owner/repo
  REMOTE_URL=$(git remote get-url origin 2>/dev/null || echo "")

  if [ -n "$REMOTE_URL" ]; then
    # Extract owner/repo from various URL formats
    OWNER_REPO=$(echo "$REMOTE_URL" | sed -E 's#.*github\.com[:/]([^/]+/[^/.]+)(\.git)?$#\1#')

    if [ -n "$OWNER_REPO" ]; then
      # Configure git to push directly to GitHub (bypassing ccweb proxy)
      DIRECT_URL="https://x-access-token:${GITHUB_TOKEN}@github.com/${OWNER_REPO}.git"
      git remote set-url --push origin "$DIRECT_URL" 2>/dev/null || true
      echo "[sessionlog-ccweb] Configured direct GitHub push access."
    fi
  fi
else
  echo "[sessionlog-ccweb] Warning: GITHUB_TOKEN not set. Session push will be limited."
fi

# ============================================================================
# Install pre-push branch filter
# ============================================================================

# Restrict direct pushes to only allowed prefixes and the current working branch.
# This prevents accidental pushes to other branches via the direct GitHub URL.

HOOKS_DIR="$(git rev-parse --git-dir)/hooks"
PRE_PUSH_HOOK="$HOOKS_DIR/pre-push"

install_push_filter() {
  mkdir -p "$HOOKS_DIR"

  # Check if pre-push hook already exists
  if [ -f "$PRE_PUSH_HOOK" ]; then
    # Check if our filter is already installed
    if grep -q "sessionlog-ccweb-push-filter" "$PRE_PUSH_HOOK" 2>/dev/null; then
      return
    fi

    # Append to existing hook
    cat >> "$PRE_PUSH_HOOK" << 'HOOKEOF'

# sessionlog-ccweb-push-filter
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
while read local_ref local_sha remote_ref remote_sha; do
  BRANCH_NAME=$(echo "$remote_ref" | sed 's#refs/heads/##')
  # Allow current working branch
  if [ "$BRANCH_NAME" = "$CURRENT_BRANCH" ]; then
    continue
  fi
  # Check allowed prefixes
  ALLOWED=false
  for prefix in ALLOWED_PUSH_PREFIXES_PLACEHOLDER; do
    case "$BRANCH_NAME" in
      "$prefix"*) ALLOWED=true; break ;;
    esac
  done
  if [ "$ALLOWED" = "false" ]; then
    echo "[sessionlog-ccweb] Blocked push to '$BRANCH_NAME' (not in allowed prefixes)"
    exit 1
  fi
done
HOOKEOF
  else
    # Create new hook
    cat > "$PRE_PUSH_HOOK" << 'HOOKEOF'
#!/bin/sh
# sessionlog-ccweb-push-filter
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
while read local_ref local_sha remote_ref remote_sha; do
  BRANCH_NAME=$(echo "$remote_ref" | sed 's#refs/heads/##')
  # Allow current working branch
  if [ "$BRANCH_NAME" = "$CURRENT_BRANCH" ]; then
    continue
  fi
  # Check allowed prefixes
  ALLOWED=false
  for prefix in ALLOWED_PUSH_PREFIXES_PLACEHOLDER; do
    case "$BRANCH_NAME" in
      "$prefix"*) ALLOWED=true; break ;;
    esac
  done
  if [ "$ALLOWED" = "false" ]; then
    echo "[sessionlog-ccweb] Blocked push to '$BRANCH_NAME' (not in allowed prefixes)"
    exit 1
  fi
done
HOOKEOF
  fi

  chmod +x "$PRE_PUSH_HOOK"
}

# Replace placeholder with actual prefixes and install
install_push_filter
if [ -f "$PRE_PUSH_HOOK" ]; then
  sed -i "s/ALLOWED_PUSH_PREFIXES_PLACEHOLDER/$ALLOWED_PUSH_PREFIXES/g" "$PRE_PUSH_HOOK"
fi

echo "[sessionlog-ccweb] Setup complete."
